2023-10-23 18:43:21,687 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-23 18:43:21,687 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Configure stats pid to 19426
2023-10-23 18:43:21,687 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Loading settings from /home/tejas/.config/wandb/settings
2023-10-23 18:43:21,687 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Loading settings from /home/tejas/Documents/SMAI/assignment-3-MrTejas/q2/wandb/settings
2023-10-23 18:43:21,687 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-23 18:43:21,687 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-23 18:43:21,687 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-23 18:43:21,687 INFO    MainThread:19426 [wandb_init.py:_log_setup():528] Logging user logs to /home/tejas/Documents/SMAI/assignment-3-MrTejas/q2/wandb/run-20231023_184321-ee7xhque/logs/debug.log
2023-10-23 18:43:21,687 INFO    MainThread:19426 [wandb_init.py:_log_setup():529] Logging internal logs to /home/tejas/Documents/SMAI/assignment-3-MrTejas/q2/wandb/run-20231023_184321-ee7xhque/logs/debug-internal.log
2023-10-23 18:43:21,688 INFO    MainThread:19426 [wandb_init.py:init():568] calling init triggers
2023-10-23 18:43:21,688 INFO    MainThread:19426 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'layer_sizes': [11, 5, 5, 6], 'batch_size': 100, 'num_epoches': 100, 'learning_rate': 0.001, 'activation_function': 'tanh', 'optimization': 'mini-batch'}
2023-10-23 18:43:21,688 INFO    MainThread:19426 [wandb_init.py:init():593] re-initializing run, found existing run on stack: dkek5hjp
2023-10-23 18:43:21,689 INFO    MainThread:19426 [wandb_run.py:_finish():1934] finishing run tejas591995/MLP_classification/dkek5hjp
2023-10-23 18:43:21,689 INFO    MainThread:19426 [jupyter.py:save_history():445] not saving jupyter history
2023-10-23 18:43:21,690 INFO    MainThread:19426 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-23 18:43:21,690 INFO    MainThread:19426 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-10-23 18:43:21,690 INFO    MainThread:19426 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-23 18:43:21,690 INFO    MainThread:19426 [wandb_run.py:_restore():2151] restore
2023-10-23 18:43:21,690 INFO    MainThread:19426 [wandb_run.py:_restore():2157] restore done
2023-10-23 18:43:45,376 INFO    MainThread:19426 [wandb_init.py:init():618] starting backend
2023-10-23 18:43:45,376 INFO    MainThread:19426 [wandb_init.py:init():622] setting up manager
2023-10-23 18:43:45,379 INFO    MainThread:19426 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-23 18:43:45,379 INFO    MainThread:19426 [wandb_init.py:init():628] backend started and connected
2023-10-23 18:43:45,403 INFO    MainThread:19426 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-23 18:43:45,404 INFO    MainThread:19426 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-23 18:43:45,404 INFO    MainThread:19426 [wandb_init.py:init():720] updated telemetry
2023-10-23 18:43:45,416 INFO    MainThread:19426 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-23 18:43:52,903 WARNING MainThread:19426 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/tejas/anaconda3/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/home/tejas/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-10-23 18:44:01,901 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-23 18:44:01,901 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Configure stats pid to 19426
2023-10-23 18:44:01,901 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Loading settings from /home/tejas/.config/wandb/settings
2023-10-23 18:44:01,901 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Loading settings from /home/tejas/Documents/SMAI/assignment-3-MrTejas/q2/wandb/settings
2023-10-23 18:44:01,901 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-23 18:44:01,901 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-23 18:44:01,902 INFO    MainThread:19426 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-23 18:44:01,902 INFO    MainThread:19426 [wandb_init.py:_log_setup():528] Logging user logs to /home/tejas/Documents/SMAI/assignment-3-MrTejas/q2/wandb/run-20231023_184401-yoeiucp2/logs/debug.log
2023-10-23 18:44:01,902 INFO    MainThread:19426 [wandb_init.py:_log_setup():529] Logging internal logs to /home/tejas/Documents/SMAI/assignment-3-MrTejas/q2/wandb/run-20231023_184401-yoeiucp2/logs/debug-internal.log
2023-10-23 18:44:01,902 INFO    MainThread:19426 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f8a85f80dc0>
2023-10-23 18:44:01,902 INFO    MainThread:19426 [wandb_init.py:init():568] calling init triggers
2023-10-23 18:44:01,902 INFO    MainThread:19426 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'layer_sizes': [11, 5, 5, 6], 'batch_size': 100, 'num_epoches': 100, 'learning_rate': 0.001, 'activation_function': 'tanh', 'optimization': 'mini-batch'}
2023-10-23 18:44:01,902 INFO    MainThread:19426 [wandb_init.py:init():618] starting backend
2023-10-23 18:44:01,902 INFO    MainThread:19426 [wandb_init.py:init():622] setting up manager
2023-10-23 18:44:01,903 INFO    MainThread:19426 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-23 18:44:01,903 INFO    MainThread:19426 [wandb_init.py:init():628] backend started and connected
2023-10-23 18:44:01,911 INFO    MainThread:19426 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-23 18:44:01,911 INFO    MainThread:19426 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-23 18:44:01,911 INFO    MainThread:19426 [wandb_init.py:init():720] updated telemetry
2023-10-23 18:44:01,921 INFO    MainThread:19426 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-23 18:45:32,041 ERROR   MainThread:19426 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-23 18:45:32,394 ERROR   MainThread:19426 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-23 18:45:53,031 WARNING MsgRouterThr:19426 [router.py:message_loop():77] message_loop has been closed
2023-10-23 18:45:53,032 WARNING MsgRouterThr:19426 [router.py:message_loop():77] message_loop has been closed
2023-10-23 18:45:53,032 WARNING MsgRouterThr:19426 [router.py:message_loop():77] message_loop has been closed
